require("dotenv").config()
const express = require("express")
const jwt = require("jsonwebtoken")
const blogRouter = require("./routers/blogRouter")
const userRouter = require("./routers/userRouter")
const commentRouter = require("./routers/commentRouter")
const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: true }))

app.use("/blog", blogRouter)
app.use("/comment", commentRouter)
app.use("/user", userRouter)
app.listen(3000, () => console.log("Server listening on port 3000!"))
